/* eslint-disable camelcase */
import {parseEther} from '.'

/**
 * This file centralizes all prices to make it easier to update them when changing fork blocks
 * Unlike other use cases, it's important to fix block when forking to having precise prices assertions
 */
const Quote = {
  arbitrum: {
    ETH_USD: parseEther('1,565'),
    USDC_USD: parseEther('1'),
    DAI_USD: parseEther('1'),
    BTC_USD: parseEther('22,321'),
  },
  avalanche: {
    BTC_USD: parseEther('20,058'),
    ETH_USD: parseEther('1,359'),
    AVAX_USD: parseEther('17'),
    UNI_USD: parseEther('6.91'),
    CRV_USD: parseEther('0.91'),
    AAVE_USD: parseEther('78'),
    CURVE_REN_LP_USD: parseEther('20,185'),
    CURVE_AAVE_LP_USD: parseEther('1.02'),
  },
  mainnet: {
    BTC_USD: parseEther('21,750'),
    ETH_USD: parseEther('1,540'),
    DOGE_USD: parseEther('0.007'),
    BTC_ETH: parseEther('14'),
    USD_ETH: parseEther('0.0007'),
    USD_BTC: parseEther('0.00005'),
    VSP_USD: parseEther('0.4472'),
    CETH_USD: parseEther('30'),
    CDAI_USD: parseEther('0.022'),
    CURVE_TRIPOOL_LP_USD: parseEther('1.022'),
    CURVE_SBTC_LP_USD: parseEther('22,236'),
    CURVE_MIM_3CRV_LP_USD: parseEther('1.001'),
    CURVE_SUSD_LP_USD: parseEther('1.057'),
    CURVE_D3POOL_LP_USD: parseEther('0.9348'),
    CURVE_FRAX_3CRV_LP_USD: parseEther('1.00'),
    CURVE_IBBTC_LP_USD: parseEther('22,130.58'),
    CURVE_MUSD_LP_USD: parseEther('1.021'),
    CURVE_AAVE_LP_USD: parseEther('1.1057'),
    CURVE_COMPOUND_LP_USD: parseEther('1.115'),
    CURVE_USDT_LP_USD: parseEther('2.939'),
    CURVE_BUSD_LP_USD: parseEther('1.133'),
    CURVE_PAX_LP_USD: parseEther('1.04'),
    CURVE_Y_LP_USD: parseEther('1.138'),
    CURVE_DOLA_3CRV_LP_USD: parseEther('1.00'),
    CURVE_DOLA_FRAXBP_LP_USD: parseEther('1.00'),
    CURVE_GUSD_LP_USD: parseEther('1.03'),
    CURVE_REN_LP_USD: parseEther('22,356.20'),
    CURVE_FRAX_USDC_LP_USD: parseEther('1.00'),
    UNIV2_ETH_DAI_LP_USD: parseEther('141'),
    UNIV2_WBTC_USDC_LP_USD: parseEther('48,938,043,997,846'),
    UNIV2_ETH_WBTC_LP_USD: parseEther('1,435,735,834'),
    vaUSDC_USD: parseEther('1.04'),
    vaDAI_USD: parseEther('1.07'),
    vaFRAX_USD: parseEther('1.04'),
    vaETH_USD: parseEther('1,582'),
    vastETH_USD: parseEther('1,582'),
    varETH_USD: parseEther('1,643'),
    vaWBTC_USD: parseEther('22,201'),
    vaLINK_USD: parseEther('6.80'),
    vacbETH_USD: parseEther('1,564'),
  },
  polygon: {
    MATIC_USD: parseEther('0.84'),
    BTC_USD: parseEther('20,060'),
    ETH_USD: parseEther('1,359'),
  },
  bsc: {
    BTC_USD: parseEther('20,058'),
    ETH_USD: parseEther('1,359'),
    BNB_USD: parseEther('266'),
    BNB_USD_2: parseEther('253'),
    BUSD_USD: parseEther('1'),
    ELLIPSIS_VAL_3EPS: parseEther('1.003'),
  },
  mumbai: {MATIC_USD: parseEther('0.84'), ETH_USD: parseEther('1,359')},
  optimism: {
    ETH_USD: parseEther('1,675'),
    USDC_USD: parseEther('1'),
    DAI_USD: parseEther('1'),
    OP_USD: parseEther('2.5'),
  },
}
export default Quote
